### ISSUE TITLE
home.php connection to index.php

### ISSUE THREAD

**Issue by PHMD** [ramiabraham/wphierarchy#11]
In the diagram, home.php does not have a connection to index.php
![screen shot 2015-02-24 at 4 38 47 pm](https://cloud.githubusercontent.com/assets/5489325/6360940/a3cee8dc-bc43-11e4-943c-cc744ad6f3b7.png)

**Comment by sistanoman** [comment]
I just noticed this as well, and confirmed it with the original diagram in the WP Codex:
https://codex.wordpress.org/File:wp-template-hierarchy.jpg

**Comment by kim07** [comment]
:+1:

**Comment by ramiabraham** [comment]
*finally* adjusted
