### ISSUE TITLE
.main Class Width Should be Omitted or Set to 100%

### ISSUE THREAD

**Issue by sistanoman** [ramiabraham/wphierarchy#13]
Currently, the page is expanding horizontally past the browser or device width and pushing content off the page. This can be fixed by omitting the width value altogether on the .main class or setting it's value from "1280" to "100%." I'm seeing this issue in the latest version of FireFox and Chrome.

**Comment by marktimemedia** [comment]
As far as I know, it's not built to be responsive at the moment.

**Comment by ramiabraham** [comment]
Considering the scope of the site, the css is deliberately not responsive.

**Comment by sistanoman** [comment]
Oops, I should have read the scope. Nice work, thanks!
