### ISSUE TITLE
Connection from &custom.php to page.php

### ISSUE THREAD

**Issue by githubsucksverybad** [ramiabraham/wphierarchy#14]
I don't understand why &custom.php and page.php are connected. 

If the $custom.php file is missing, doesn't Wordpress **always** check for a page-$slug.php or a page-$id.php file? 

I can't imagine any scenario where Wordpress would - in case of a missing $custom.php file - skip the search for the page-$slug.php and page-$id.php files.

**Comment by ramiabraham** [comment]
It can be *either*, depending on how it's being used. This is indicated in the existing design with a connection from $custom to both page.php *as well as* page-$slug / page-$id:

[$custom page - template hierarchy example](http://i.imgur.com/1DhEf1u.png)
