### ISSUE TITLE
Declare license

### ISSUE THREAD

**Issue by moorereason** [ramiabraham/wphierarchy#18]
Is this project licensed as open source?

**Comment by electronthemes** [comment]
yes

**Comment by moorereason** [comment]
@electronthemes, please elaborate.  I see no evidence of a license declaration.

**Comment by ramiabraham** [comment]
Added in https://github.com/ramiabraham/wphierarchy/commit/50a85d57b8c8b37fe712b4a62142ad2b23a3380a.
