### ISSUE TITLE
Add new embed templates to hierarchy

### ISSUE THREAD

**Issue by sc0ttkclark** [ramiabraham/wphierarchy#20]
https://make.wordpress.org/core/2016/03/11/embeds-changes-in-wordpress-4-5/

**Comment by ramiabraham** [comment]
Added (finally) in https://github.com/ramiabraham/wphierarchy/commit/49c99e94ec3eecec1c62b418b08955920ba369e1

**Comment by sc0ttkclark** [comment]
Yesssss
