### ISSUE TITLE
Secrets secrets are no fun...

### ISSUE THREAD

**Issue by tnorthcutt** [ramiabraham/wphierarchy#23]
...[secrets secrets hurt someone](https://github.com/ramiabraham/wphierarchy/commit/49c99e94ec3eecec1c62b418b08955920ba369e1#diff-04c6e90faac2675aa89e2176d2eec7d8R57).

**Comment by ramiabraham** [comment]
:) They're not quite done, so I didn't want to advertise them just yet. In the meantime, try typing:

`dark`
`light`
`mono`

And if you're adventurous, type the name of main character in `The Matrix`.

**Comment by tnorthcutt** [comment]
![cat-tambo](https://cloud.githubusercontent.com/assets/796639/16428693/dec93fd0-3d27-11e6-86c2-c0d346934dbc.gif)
